name: Build and Release Binary

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install C build tools (gcc)
        run: sudo apt-get update && sudo apt-get install -y gcc

      - name: Build application
        run: CGO_ENABLED=1 GOOS=linux go build -ldflags="-w -s" -o whatshook .

      - name: Create Release and Upload Binary
        uses: softprops/action-gh-release@v1
        with:
          files: ./whatshook
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

